# Site settings
name: zmNinja
title: zmNinja
email: pliablepixels@gmail.com
description: "Better than sliced toast by 73%. FDA might have said so"
baseurl: ""
url: "http://localhost:4000"
disqusid: zmNinja
host: "0.0.0.0"

# Build settings
markdown: kramdown
permalinks: pretty
